[workspace]
members = [
    "crates/core",
    "crates/matrix",
    "crates/test"
]
resolver = "1"

[workspace.dependencies]
anyhow = "1.0.75"
reqwest = "0.11.22"
serde = "1.0.192"
url = { version = "2.4.1", features = ["serde"] }
