[workspace]
members = [
    "crates/core",
    "crates/matrix",
    "crates/server",
    "crates/test"
]
default-members = ["crates/server"]
resolver = "1"

[workspace.dependencies]
anyhow = "1.0.75"
axum = { version = "0.7.4", features = ["tokio"] }
dotenv = "0.15.0"
http = "0.2.11"
reqwest = { version = "0.11.22", default-features = false, features = ["blocking", "json", "rustls", "stream", "multipart"] }
openssl = { version = "0.10.63", features = ["vendored"] }
openssl-sys = { version = "0.9.99", features = ["vendored"] }
serde = "1.0.192"
serde_json = "1.0.108"
tokio = "1.34.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.6.1", features = ["v4"] }
url = "2.4.1"
