[package]
name = "core"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "commune"
path = "src/lib.rs"

[dependencies]
handlebars = "4.5.0"
lettre = "0.11"
rand = "0.8.5"
redis = { version = "0.24.0", features = ["aio", "tokio-comp"] }
thiserror = "1.0.50"
validator = { version = "0.16", features = ["derive"] }

# Workspace
http = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }

# Local Dependencies
matrix = { path = "../matrix" }
