[package]
name = "core"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "commune"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0.50"
validator = { version = "0.16", features = ["derive"] }

# Workspace
http = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }

# Local Dependencies
matrix = { path = "../matrix" }
