name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    paths:
      - "**"
      - "!/*.md"
      - "!/**.md"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Unit Tests
        run: cargo test -p matrix

      - name: E2E Tests
        env:
          COMMUNE_SYNAPSE_HOST: 'http://localhost:8008'
        run: |
          cp ./.env.example ./.env
          docker compose up -d
          sleep 10
          cargo test -p test -- --test-threads=1
          sleep 10
          docker compose down
          docker ps
