name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    paths:
      - "**"
      - "!/*.md"
      - "!/**.md"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Unit Tests
        run: cargo test -p matrix

      - name: Create a copy of `.env.example`
        run: cp ./.env.example ./.env

      - name: Generate Synapse Configuration
        run: |
          docker run -i --rm -v ./docker/synapse:/data \
            --env-file .env \
            matrixdotorg/synapse:v1.96.1 generate

      - name: Use Test Homeserver
        run: |
          sudo cp -f ./crates/test/fixtures/synapse/homeserver.yaml ./docker/synapse/homeserver.yaml

      - name: Retrieve Admin Access Token
        run: |
          export COMMUNE_SYNAPSE_ADMIN_TOKEN=$(PGPASSWORD=secretpassword docker compose exec -it synapse_database \
            psql -d synapse -U synapse_user --no-align --quiet --tuples-only \
            -c "SELECT a."token" FROM users u LEFT JOIN access_tokens a ON a.user_id=u."name" WHERE u."admin"=1")
          echo "COMMUNE_SYNAPSE_ADMIN_TOKEN=${COMMUNE_SYNAPSE_ADMIN_TOKEN}" >> $GITHUB_ENV

      - name: E2E Tests
        run: |
          docker compose up -d
          sleep 10
          cargo test -p test -- --test-threads=1

      - name: Print Logs
        if: always()
        run: |
          docker-compose logs --no-color --tail=1000 synapse > synapse.log
          cat ./synapse.log
          docker compose down
          docker ps
